eobsystems_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls')), 
    path('systems/', include('systems_products.urls')), 
    path('services/', include('services.urls')), 
    path('news-update/', include('news_update.urls', namespace='news_update')), 
    path('contact-us/', include('contacts_page.urls')), 
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news_update/urls.py
from django.urls import path

from . import views

app_name = 'news_update'

urlpatterns = [
    path('', views.post_list, name='news-update'), 
    path('tag/<slug:tag_slug>', views.post_list, name='post_list_by_tag'), 
    path('<slug:slug_p>/', views.post_detail, name='news-update-detail'), 
]

pages/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name='index'), 
    path('about-us', views.about, name='about-us'), 
    path('career', views.career, name='career'), 
]

news_update/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from django.urls import reverse
from taggit.managers import TaggableManager

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    author = models.ForeignKey(User, on_delete=models.PROTECT, related_name='blog_post')
    body = RichTextField(blank=True, null=True)
    photo = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
    objects = models.Manager()
    published = PublishedManager() #custom manager
    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse('news_update:news-update-detail', args=[self.slug])

    class Meta:
        ordering = ('-publish',)
        verbose_name = 'News and Update'
        verbose_name_plural = 'News and Update'
    
    def __str__(self):
        return self.title

news_update/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Post
from taggit.models import Tag
from django.db.models import Count
from systems_products.models import SystemsProduct


def post_list(request, tag_slug=None):
    products = SystemsProduct.objects.order_by('order_by').filter(is_published=True)
    object_list = Post.published.all()

    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)

    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)

    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)

    context = {
        'page': page,
        'posts': posts,
        'tag': tag,
        'products':products,
    }
    return render(request,'news_update/news_update_list.html', context)


def post_detail(request, slug_p):
    products = SystemsProduct.objects.order_by('order_by').filter(is_published=True)
    post = get_object_or_404(Post, slug=slug_p, status='published')

    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', 'publish')[:3]
    
    context = {
        'post': post,
        'similar_posts': similar_posts,
        'products':products,
    }

    return render(request, 'news_update/news_update_details.html', context)

templates/news_update/news_update_details.html
{% extends 'base.html' %}
{% load static %}
{% block pagetitle %} News & Update - {{ post.title }}{% endblock %}

{% block content %}

<!-- Hero Section -->
<div class="hero-banner hero-banner__inner" style=" background-image: linear-gradient(to right bottom, rgba(34,63,154,0.8), rgba(27,44,95,0.8)), url({% static 'images/hero-image.jpg' %});">
    <div class="hero-banner__text-box">
        <h1 class="heading-primary-main heading-primary-main-inner">News & Update</h1>
    </div>
</div>


<div class="category-page">
    <div class="wrapper row--b-padding">
    
        {% if post %}
           
                <div class="row row--gutters generic-content-container">
                    <div class="row__medium-3 margin-top">

                        {% if similar_posts %}
                            <h3 class="section-heading-sub">Similar Posts</h3>
                            {% for post in similar_posts %}

                                <ul class="section-heading-sub-ul">

                                    <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
                                
                                </ul>
                            
                            {% empty %}

                                <p>There are no similar posts yet.</p>
                            
                            {% endfor %}

                        {% else %}
                            <p>&nbsp;</p>
                        {% endif %}
                    </div>

                    <div class="row__medium-8">
                        <h2 class="section-heading row--t-padding">{{post.title}}</h2>
                        <p class="date">{{ post.publish }}</p>
                        <div class="row__medium-wrapper">
                            <img src="{{post.photo.url }}" alt="{{post.title}}" class="margin-btm">
                            
                            {{post.body | safe}}
                        </div>
                    </div>
                    
                </div>
           
        {% else %}
            <p>No available post</p>
        {% endif %}
    </div>
</div>

{% endblock %}

templates/news_update/news_update_list.html
{% extends 'base.html' %}
{% load static %}
{% block pagetitle %} News & Update {% endblock %}

{% block content %}

<!-- Hero Section -->
<div class="hero-banner hero-banner__inner" style=" background-image: linear-gradient(to right bottom, rgba(34,63,154,0.8), rgba(27,44,95,0.8)), url({% static 'images/hero-image.jpg' %});">
    <div class="hero-banner__text-box">
        <h1 class="heading-primary-main heading-primary-main-inner">News & Update</h1>
    </div>
</div>


<div class="category-page">
    <div class="wrapper row--b-padding">
        
        
        {% if posts %}

        {% if tag %}
            <h2 class="section-heading row--t-padding">Posts tagged with "{{ tag.name }}"</h2>
        {% endif %}

        {% for post in posts %}
            <div class="row row--gutters generic-content-container">
                <h2 class="section-heading row--t-padding">&nbsp;</h2>
                <div class="row__medium-3">
                    <img src="{{post.photo.url }}" style=" width: 100%; height: 250px; object-fit: cover; object-position: center center" alt="Product Name">
                </div>
            
                <div class="row__medium-8">
                    <div class="row__medium-wrapper">
                        <h3 class="list-title">
                            <a href="{{ post.get_absolute_url }}">{{post.title}}</a>
                        </h3>
                        <p class="date">{{ post.publish }}</p>
                        
                        <p class="tags">
                            Tags:
                            {% for tag in post.tags.all %}
                              <a href="{% url 'news_update:post_list_by_tag' tag.slug %}">
                                {{ tag.name }}
                              </a>
                              {% if not forloop.last %} {% endif %}
                            {% endfor %}
                          </p>

                        {{post.body | safe | truncatewords:30 | linebreaks  }}
                        <p><a href="{{ post.get_absolute_url }}" class="btn primary-btn">Read More</a></p>
                    </div>
                </div>
            </div>
        {% endfor %}

        {% else %}
            <p>No available post</p>
        {% endif %}

        {% include "news_update/pagination.html" with page=posts %}

    </div>
</div>

{% endblock %}

templates/news_update/pagination.html
<div class="pagination">
    <span class="step-links">
      {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
      {% endif %}
      <span class="current">
        Page {{ page.number }} of {{ page.paginator.num_pages }}.
      </span>
      {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
      {% endif %}
    </span>
  </div>