eobsystems_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls')), 
    path('systems/', include('systems_products.urls')), 
    path('services/', include('services.urls')), 
    path('news-update/', include('news_update.urls', namespace='news_update')), 
    path('contact-us/', include('contacts_page.urls')), 
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news_update/urls.py
from django.urls import path

from . import views

app_name = 'news_update'

urlpatterns = [
    path('', views.post_list, name='news-update'), 
    path('tag/<slug:tag_slug>', views.post_list, name='post_list_by_tag'), 
    path('<slug:slug_p>/', views.post_detail, name='news-update-detail'), 
]

pages/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name='index'), 
    path('about-us', views.about, name='about-us'), 
    path('career', views.career, name='career'), 
]

systems_products/urls.py
from django.urls import path

from . import views

app_name = 'systems_product'

urlpatterns = [
    path('', views.systems_products, name='systems_products'), 
    path('<slug:c_slug>/', views.systems_product_details, name='systems_product_details'), 
]

templates/partials/_alerts.html
{% if messages %}
    {% for message in messages %}
        <div id="message" class="container-box">
            <div class="alert alert-{{messages.tags}} alert-dismissible text-center" role="alert">
                
                <strong>
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        Error: 
                    {% else %}
                        {{ message.tags|title }}
                    {% endif %}
                    {{ message }}
                </strong>
            </div>
        </div>
    {% endfor %}
{% endif %}

templates/partials/_footer.html
<footer class="footer-section">
    <div class="wrapper">
        <div class="row row--gutters">
            <div class="row__medium-6">
                <p>For inquries call:<a href="tel:639666429400" title="+63 966 642 9400" style="display:inline-block; font-size: .96rem;">+63 966 642 9400</a> | <a href="tel:639394645875" title="+63 939 464 5875" style="display:inline-block; font-size: .96rem;">+63 939 464 5875</a></p>
                <p>Copyright © <span class="year"></span> EOBSYSTEMS.COM.  All rights reserved.</p>
            </div>
            <div class="row__medium-6">
                <ul>
                    <li><a href="{% url 'services' %}">Services</a></li>
                    <li><a href="{% url 'about-us' %}">About Us</a></li>
                    <li><a href="{% url 'career' %}">Career</a></li>
                    <li><a href="{% url 'contact-us' %}">Contact Us</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>

<script>
    
    function mouseOver() {
        document.getElementById("showMegaMenu").classList.add("hover");
    }
      
    function mouseOut() {
        document.getElementById("showMegaMenu").classList.remove("hover");
      }
</script>   

templates/partials/_navbar.html
<div class="wrapper-nav">
    <div id="menu_mobile" class="menu_mobile_expansion">
        <div class="close-nav">
            <i class="fas fa-times-circle"></i>
        </div>
        
        <div class="site-header__main-nav">
                <nav class="primary-nav">
                    <ul>
                        <li><a href="{% url 'index' %}" {% if '/' == request.path %}class="is-current-link" {% endif %} >Home</a></li>
                        <li onmouseover="mouseOver()" onmouseout="mouseOut()">
                            <a href="#" {% if 'systems' in request.path %}class="is-current-link" {% endif %}>Systems <i class="fas fa-angle-down fa-xs"></i></a>
                            
                            <div id="showMegaMenu" class="menu-box">
                                <div class="dropdown-content">
                                    
                                    {% for item in products %}
                                        <a href="{% url 'systems_product:systems_product_details' item.slug %}">{{item.title}}</a>
                                    {% endfor %}
                                </div>
                            </div>
                        </li>
                        <li><a href="{% url 'services' %}" {% if 'services' in request.path %}class="is-current-link" {% endif %}>Services</a></li>
                        <li><a href="{% url 'news_update:news-update' %}" {% if 'news-update' in request.path %}class="is-current-link" {% endif %}>News & Update</a></li>
                        <li><a href="{% url 'about-us' %}" {% if 'about-us' in request.path %} class="is-current-link" {% endif %}>About Us</a></li>
                        <li><a href="{% url 'contact-us' %}"{% if 'contact-us' in request.path %} class="is-current-link" {% endif %}>Contact</a></li>
                    </ul>
                </nav>
        
        </div>
    </div>
</div>

templates/partials/_topbar.html
{% load static %}
 <div class="wrapper">
    <div class="site-header__main-logo">
        <a href="{% url 'index' %}"> <img src="{% static 'images/eob-logo-2.png' %}" alt="EOB Logo" /></a>
    </div>
</div>    
<div class="wrapper-main">
    <div class="wrapper-nav">
        <div class="site-header__top-nav">                
            <ul>
                <li><a href="tel:639666429400" title="+63 966 642 9400">+63 966 642 9400</a></li>
                <li><a href="tel:639394645875" title="+63 939 464 5875">+63 939 464 5875</a></li>
                <li><a href="mailto:adminsupport@eobsystem.com" title="info@eobsystems.com">sales@eobsystems.com</a></li>
                <!-- <li><a href="https://www.facebook.com" title="Facebook Account"><i class="fab fa-facebook-f"></i></a></li> -->
            </ul>     
        </div>
    </div>
</div>
<div class="wrapper">
    <div class="site-header__menu-icon">
        <div class="site-header__menu-icon__middle">
            <i class="fas fa-bars"></i>
        </div>
    </div> 
</div>    